[package]
name = "cargo-preset"
version = "0.1.0"
edition = "2021"

[dependencies]
toml_edit = { version = "0.22.9", default-features = false, features = ["parse"] }

[profile.release]
strip = true
lto = "thin"
panic = 'abort'
incremental = false
codegen-units = 1
